global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3003']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3004']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3005']
